name: rooster
description: Report no. 1 Automation
version: 1.0.1+2
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # background stuff
  flutter_local_notifications: ^1.4.4+4
  # storage stuff
  shared_preferences: '>=0.5.8 <2.0.0'
  sqflite: ^1.2.1
  flutter_secure_storage: ^3.3.3
  # web
  http: ^0.12.2
  webview_flutter: ^0.3.22+1
  webview_cookie_manager: ^1.0.3
  cookie_jar: ^1.0.0
  # other
  cloud_firestore: ^0.14.0+2
  firebase_core: "0.5.0"
  uuid: 2.2.0
  flutter_json_widget: ^1.0.1
  logger:
    git: git@github.com:roisnir/logger.git
  path_provider: ^1.6.14
#  workmanager: ^0.2.0
  open_file: ^3.0.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/strings/
    - assets/graphics/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/graphics/rooster_icon_256.png"